config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations',passwords: 'users/passwords'}
  # 以下を追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_sign_in', to: 'users/sessions#admin_sign_in'
  end
  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end

  resources :foods do
    resource :favorites, only: [:create, :destroy]
  end
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'

  resources :plans do
    resources :comments
  end
  resources :favorites, only: [:favorites, :create, :destroy]
  root 'foods#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :contacts, only: [:new, :create, :destroy] 
  resources :maps, only: [:index]
  resources :others, only: [:index]
  resources :wethers, only: [:index]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods
  has_many :favorites, dependent: :destroy
  has_many :favorite_foods, through: :favorites, source: :food
  has_many :plans

  def favorited_by?(food_id)
    favorites.where(food_id: food_id).exists?
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def self.admin
    find_or_create_by!(email: 'guest_admin@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "管理者ゲストユーザー"
      user.admin = true
    end
  end

  validates :name, presence: true

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == 'guest@example.com'
      redirect_to new_user_session_path, alert: 'ゲストユーザーのパスワード再設定はできません。'
    end
  end
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  protected
  # アカウント編集後、プロフィール画面に移動する
  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end

  def ensure_normal_user
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーの更新・削除はできません。。'
    end
  end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end

  def admin_sign_in
    user = User.admin
    sign_in user
    redirect_to root_path, notice: '管理者ユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to user_path(@user.id)
      else
        render :new
    end
  end

  def show
    @user = current_user
    @foods = @user.foods

    favorites = Favorite.where(user_id: current_user.id).pluck(:food_id)
    @favorite_list = Food.find(favorites)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_show_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
  params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/create.erb
$("#favorite_<%= @food.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { food: @food }) %>");

app/views/users/destroy.erb
$("#favorite_<%= @food.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { food: @food }) %>");

app/views/users/edit.html.erb
<div class="form-groups">
  <h1>プロフィールを編集する</h1>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <%= form_with model: @user, local: true do |form| %>
      <dl>
        <dt>ユーザー名</dt>
        <dd class="form-contact"><%= form.text_field :name %></dd>
      </dl>
      <dl>
        <dt>メールアドレス</dt>
        <dd class="form-contact"><%= form.email_field :email %></dd>
      </dl>
      <dl>
        <dt><%= form.submit "保存" %></dt>
      </dl>
    <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="users-show">
  <h3><%= current_user.name %> マイページ</h3>
  <table>
    <tr class="users-show-edit">
      <td class="users-show-edit">お名前：<%= current_user.name %></td>
    </tr>
    <tr>
      <td class="users-show-edit">メールアドレス：<%= current_user.email %></td>
    </tr>
  </table>
  <div class="profile-edit">
    <i class="fa-solid fa-pencil"></i>
    &nbsp;<%= link_to "プロフィール編集", edit_user_path(current_user), data: {"turbolinks" => false} %>
  </div>
</div>

<div class="food-container-favorites">
  <table>
    <% if @favorite_list.present? %>
      <% @favorite_list.each do |food| %>
        <tbody id="food_<%= food.id %>" class="food-container">
          <tr>
            <td>
              <%= link_to (food_path(food)) do%>
                <%= image_tag food.images.first.variant(resize: "225") if food.images.count.positive? %>
              <% end %>
            </td>
          </tr>
          <tr>
            <td class="food-name">
              <%= food.item_name %>
            </td>
          </tr>
          <tr>
            <td>
              品種：<%= food.variety %>
            </td>
          </tr>
          <tr>
            <td>
              収穫予定日：<%= food.harvest %>
            </td>
          </tr>
          <tr>
            <td class="food-comment-continue">
            <%= food.comment %>
            </td>
          </tr>
          <tr>
            <td>
              <%= link_to '続きを読む', food_path(food) %>
              <i class="fa-solid fa-angles-right"></i>
            </td>
          </tr>
          <tr>
            <td class="price-red">
              <%= food.price %>
            </td>
          </tr>
          <% if current_user&.admin %>
          <tr>
            <td>
              <%= link_to 'フード情報更新・管理', food_path(food) %>
              <i class="fa-solid fa-pencil"></i>
            </td>
          </tr>
          <% end %>
          <% if !current_user%>
          <tr>
            <td>
              <%= link_to "javascript:alert('ログインしてください');", class: "favorite-link" do %>
                <i class="fa fa-heart unlike-btn fa-lg"></i>
              <% end %>
              <%= food.favorites.count %>
            </td>
            <td></td>
              <% elsif current_user.favorited_by?(food.id) %>
            <td>
              <%= link_to favorite_path(food), class: "favorite-link", method: :DELETE, remote: true do %>
                お気に入り解除<i class="fa fa-heart unlike-btn fa-lg"></i>
              <% end %>
              <%= food.favorites.count %>
            </td>
            <% else %>
            <td>
              <%= link_to create_favorite_path(food), class: "favorite-link", method: :POST, remote: true do %>
                お気に入り<i class="fa fa-heart like-btn fa-lg"></i>
              <% end %>
              <%= food.favorites.count %>
            </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    <% end %>
  </table>
</div>

<% if current_user&.admin %>
  <div class="button-blue">
    <i class="fa-regular fa-pen-to-square"></i>
    &nbsp;<%= link_to '新規登録', new_food_path %>
  </div>
  <div class="button-white">
    <%= link_to "今後のスケジュール", plans_path(current_user) %>
    &nbsp;<i class="fa-solid fa-angles-right"></i>
  </div>
<% end %>