config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations',passwords: 'users/passwords'}
  # 以下を追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_sign_in', to: 'users/sessions#admin_sign_in'
  end
  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end

  resources :foods do
    resource :favorites, only: [:create, :destroy]
  end
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'

  resources :plans do
    resources :comments
  end
  resources :favorites, only: [:favorites, :create, :destroy]
  root 'foods#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :contacts, only: [:new, :create, :destroy] 
  resources :maps, only: [:index]
  resources :others, only: [:index]
  resources :wethers, only: [:index]
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :message, presence: true
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def edit
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to new_contact_path, notice: 'お問い合わせありがとうございます！営業日2〜3日でご返信いたします。'
    else
      render :new
    end
  end

  def destroy
    @contact.destroy
  end

  private
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "件のエラー") %> が発生したため送信されませんでした。</h2>
      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3 class="contact">お問い合わせ</h3>
  <dl>
    <dt><%= form.label :お名前 %></dt>
    <dd class="form-contact"><%= form.text_field :name, placeholder: "岡本 太郎" %></dd>
  </dl>
  <dl>
    <dt><%= form.label :メールアドレス %></dt>
    <dd class="form-contact"><%= form.text_field :email, placeholder: "tarogeijutsu@gmail.com" %></dd>
  </dl>
  <dl>
    <dt><%= form.label :お問い合わせ内容 %></dt>
    <dd class="form-contact"><%= form.text_area :message, placeholder: "例)トマトは毎年何月ぐらいに収穫しますか？" %></dd>
  </dl>
  <div class="actions">
    <%= form.submit  "送信" %>
  </div>
<% end %>

app/views/contacts/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @contact, local: true) do |form| %>
  <%= form.hidden_field :name %>
  <%= form.hidden_field :email %>
  <%= form.hidden_field :message %>

  <p>お名前:<%= @contact.name %></p>
  <p>メールアドレス:<%= @contact.email %></p>
  <p>内容:<%= @contact.message %></p>
  <%= form.submit  "送信" %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: '本当に消していいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<p id="notice"><%= notice %></p>

<div class="form-groups">
  <%= render 'form', contact: @contact %>
</div>

<div class="button-white-small">
  <p class="arrow">
    <i class="fa-solid fa-angle-left"></i>
    <%= link_to 'トップページ', foods_path %>
  </p>
</div>

<% if current_user %>
  <div class="button-white-small">
    <p class="arrow">
      <i class="fa-solid fa-user"></i>
      <%= link_to 'マイページ', users_show_path %>
    </p>
  </div>
<% end %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>
<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>
<p>
  <strong>Content:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>