config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations',passwords: 'users/passwords'}
  # 以下を追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_sign_in', to: 'users/sessions#admin_sign_in'
  end
  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end

  resources :foods do
    resource :favorites, only: [:create, :destroy]
  end
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'

  resources :plans do
    resources :comments
  end
  resources :favorites, only: [:favorites, :create, :destroy]
  root 'foods#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :contacts, only: [:new, :create, :destroy] 
  resources :maps, only: [:index]
  resources :others, only: [:index]
  resources :wethers, only: [:index]
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, optional: true

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  validates :item_name,  presence: true, length: { maximum: 255 }
  validates :comment,  presence: true, length: { maximum: 255 }
  validates :harvest,  presence: true, length: { maximum: 255 }
  validates :price,  presence: true
end

app/controllers/admin/foods_controller.rb
class Admin::FoodsController < ApplicationController
  before_action :if_not_admin
  before_action :set_food, only: [:show, :edit, :destroy]

    def index
      @foods = Food.all
    end

    def show
      @favorite = current_user.favorites.find_by(food_id: @food.id)
    end

    def new
      @food = Food.new
    end

    def edit
    end

    def create
      @food = Food.new(food_params)
      if @food.save
        NoticeMailer.sendmail_food(@food).deliver_later
        redirect_to foods_path, notice: 'Food was successfully created.'
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end

    def update
      respond_to do |format|
        if @food.update(food_params)
          format.html { redirect_to food_url(@food), notice: "Food was successfully updated." }
        else
          format.html { render :edit, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @food.destroy

      respond_to do |format|
        format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      end
    end


    private

    def if_not_admin
      redirect_to root_path unless current_user.admin?
    end

    def set_food
      @food = Food.find(params[:id])
    end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :check_admin, only: [:new, :edit, :update, :destroy, :create]

  def index
    @foods = Food.all.order(created_at: :desc)
    @q = Food.ransack(params[:q])
    @foods = @q.result(distinct: true).order(created_at: :desc)
    @foods = @foods.page(params[:page]).per(8)
  end

  def show
    @favorite = Favorite.find_by(food_id: @food.id)
  end

  def new
    @food = Food.new
  end

  def edit
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      NoticeMailer.sendmail_food(@food).deliver
      redirect_to foods_path, notice: 'フードを新規登録しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: "フードの更新をしました" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: "フードを削除しました" }
    end
  end

  private

    def set_food
      @food = Food.find(params[:id])
    end

    def food_params
      params.require(:food).permit(:item_name, :variety, :comment, :storage_method, :harvest, :price, :stock, images: [])
    end

    def check_admin
      return if current_user.admin
      redirect_to root_path
    end
end

app/helpers/admin/foods_helper.rb
module Admin::FoodsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_food.html.erb
<tr>
  <td>
    <%= link_to (food_path(food)) do%>
      <%= image_tag food.images.first.variant(resize: "225") if food.images.count.positive? %>
    <% end %>
  </td>
</tr>
<tr>
  <td class="food-name">
    <%= food.item_name %>
  </td>
</tr>
<tr>
  <td>
    品種：<%= food.variety %>
  </td>
</tr>
<tr>
  <td>
    収穫予定日：<%= food.harvest %>
  </td>
</tr>
<tr>
  <td class="food-comment-continue">
  <%= food.comment %>
  </td>
</tr>
<tr>
  <td>
    <%= link_to '続きを読む', food_path(food) %>
    <i class="fa-solid fa-angles-right"></i>
  </td>
</tr>
<tr>
  <td class="price-red">
    <%= food.price %>
  </td>
</tr>
<% if current_user&.admin %>
<tr>
  <td>
    <%= link_to 'フード情報更新・管理', food_path(food) %>
    <i class="fa-solid fa-pencil"></i>
  </td>
</tr>
<% end %>
<% if !current_user%>
<tr>
  <td>
    <%= link_to "javascript:alert('ログインしてください');", class: "favorite-link" do %>
      <i class="fa fa-heart unlike-btn fa-lg"></i>
    <% end %>
    <%= food.favorites.count %>
  </td>
  <td></td>
    <% elsif current_user.favorited_by?(food.id) %>
  <td>
    <%= link_to favorite_path(food), class: "favorite-link", method: :DELETE, remote: true do %>
      お気に入り解除<i class="fa fa-heart unlike-btn fa-lg"></i>
    <% end %>
    <%= food.favorites.count %>
  </td>
  <% else %>
  <td>
    <%= link_to create_favorite_path(food), class: "favorite-link", method: :POST, remote: true do %>
      お気に入り<i class="fa fa-heart like-btn fa-lg"></i>
    <% end %>
    <%= food.favorites.count %>
  </td>
  <% end %>
</tr>

app/views/foods/_form.html.erb
<%= form_with(model: food, local: true) do |form| %>
  <% if food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food.errors.count, "件のエラー") %> が発生したため食品情報は保存されませんでした。</h2>

      <ul>
        <% food.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field field-input">
    <%= form.label :品名 %>
    <%= form.text_field :item_name %>
  </div>

  <div class="field field-input">
    <%= form.label :品種 %>
    <%= form.text_field :variety %>
  </div>

  <div class="field field-input">
    <%= form.label :内容 %>
    <%= form.text_area :comment %>
  </div>

  <div class="field field-input">
    <%= form.label :保存方法 %>
    <%= form.text_field :storage_method %>
  </div>

  <div class="field field-input">
    <%= form.label :収穫予定日 %>
    <%= form.text_field :harvest %>
  </div>

  <div class="field field-input">
    <%= form.label :料金 %>
    <%= form.text_field :price %>
  </div>

  <div class="field field-input">
    <%= form.label :在庫 %>
    <%= form.number_field :stock %>
  </div>

  <div class="field">
    <%= form.label :画像 %>
    <%= form.file_field :images,multiple: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/foods/create.erb
$("#favorite_<%= @food.id %>").html("<%= j(render partial: 'favorites/favorite', locals: { food: @food }) %>");

app/views/foods/edit.html.erb
<div class="form-groups">
  <h1>編集する</h1>

  <%= render 'form', food: @food %>

  <div class="button-blue">
    <i class="fa-solid fa-circle-check"></i>
    &nbsp;<%= link_to '確認', @food %>
  </div>

  <div class="button-white">
    <i class="fa-solid fa-angle-left"></i>
    &nbsp;<%= link_to '戻る', foods_path %>
  </div>
</div>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<ul class="slideshow-zoom">
  <li><%= image_tag (asset_path'main_01.jpg') %></li>
  <li><%= image_tag (asset_path'main_02.jpg') %></li>
  <li><%= image_tag (asset_path'main_03.jpg') %></li>
  <li><%= image_tag (asset_path'main_04.jpg') %></li>
</ul>

<h1 class="concept">10/5 開発途中です。<br>内山農園ではSDGsの一環としてフードロスに取り組んでます。</br>お近くに住む方たちに、採れたての野菜をお手頃価格でご提供しております。</br>収穫予定日をメールで予めお知らせし、 ご来店いただいた方順に販売しています。</h1>

<div class="search-container">
  <%= search_form_for @q do |f| %>
    <%= f.label :item_name_or_variety_or_comment_or_storage_method_or_harvest_or_price_cont, "野菜や果物名を入力してください。" %>
    <%= f.search_field :item_name_or_variety_or_comment_or_storage_method_or_harvest_or_price_cont, placeholder: "例)じゃがいも" %>
    <%= f.submit "検索" %>
  <% end %>
</div>
<div class="foodsTop-container">
  <% @foods.each do |food| %>
    <div class="food-container">
      <table id="food_<%= food.id %>">
        <tr>
          <td>
            <%= link_to (food_path(food)) do%>
              <%= image_tag food.images.first.variant(resize: "225") if food.images.count.positive? %>
            <% end %>
          </td>
        </tr>
        <tr>
          <td class="food-name">
            <%= food.item_name %>
          </td>
        </tr>
        <tr>
          <td>
            品種：<%= food.variety %>
          </td>
        </tr>
        <tr>
          <td>
            収穫予定日：<%= food.harvest %>
          </td>
        </tr>
        <tr>
          <td class="food-comment-continue">
          <%= food.comment %>
          </td>
        </tr>
        <tr>
          <td>
            <%= link_to '続きを読む', food_path(food) %>
            <i class="fa-solid fa-angles-right"></i>
          </td>
        </tr>
        <tr>
          <td class="price-red">
            <%= food.price %>
          </td>
        </tr>
        <% if current_user&.admin %>
        <tr>
          <td>
            <%= link_to 'フード情報更新・管理', food_path(food) %>
            <i class="fa-solid fa-pencil"></i>
          </td>
        </tr>
        <% end %>
        <% if !current_user%>
        <tr>
          <td>
            <%= link_to "javascript:alert('ログインしてください');", class: "favorite-link" do %>
              <i class="fa fa-heart unlike-btn fa-lg"></i>
            <% end %>
            <%= food.favorites.count %>
          </td>
          <td></td>
            <% elsif current_user.favorited_by?(food.id) %>
          <td>
            <%= link_to favorite_path(food), class: "favorite-link", method: :DELETE, remote: true do %>
              お気に入り解除<i class="fa fa-heart unlike-btn fa-lg"></i>
            <% end %>
            <%= food.favorites.count %>
          </td>
          <% else %>
          <td>
            <%= link_to create_favorite_path(food), class: "favorite-link", method: :POST, remote: true do %>
              お気に入り<i class="fa fa-heart like-btn fa-lg"></i>
            <% end %>
            <%= food.favorites.count %>
          </td>
          <% end %>
        </tr>
      </table>
    </div>
  <% end %>
</div>
</hr>
<div class="admin-top">
  <% if current_user&.admin %>
    <h3>管理者用 登録・スケジュール</h3>
    <div class="button-blue">
      <i class="fa-regular fa-pen-to-square"></i>
      &nbsp;<%= link_to '新規登録', new_food_path %>
    </div>
    <div class="button-white">
      <%= link_to "今後のスケジュール", plans_path(current_user) %>
      &nbsp;<i class="fa-solid fa-angles-right"></i>
    </div>
  <% end %>
</div>

<%= paginate @foods %>

<script>
$(function(){
  $(".slideshow-zoom li").css({"position":"relative"});
  $(".slideshow-zoom li").hide().css({"position":"absolute","top":0,"left":0});
  setInterval(function(){
    var $active = $(".slideshow-zoom li.zoom");
    var $next = $active.next("li").length?$active.next("li"):$(".slideshow-zoom li:first");
    $active.fadeOut(5000).removeClass("zoom");
    $next.fadeIn(5000).addClass("zoom");
  },5000);
});
</script>

app/views/foods/new.html.erb
<div class="form-groups">
  <h1>新しい収穫物を登録する</h1>

  <%= render 'form', food: @food %>

  <div class="button-white-small">
    <p class="arrow">
      <i class="fa-solid fa-angle-left"></i>
      <%= link_to 'トップページへ戻る', foods_path %>
    </p>
  </div>
</div>

app/views/foods/show.html.erb
<div class="food_show_container">
  <div class="foods_show_images">
    <div class="main-img js-main-img">
      <%= image_tag @food.images.first %>
    </div>
    <ul class="sub-img js-sub-img">
      <% @food.images.each do |image|%>
        <li><%= image_tag image.variant(resize: "460")%></li>
      <% end %>
    </ul>
  </div>

  <div class="foods-groups">
    <h1 class="food-show-h1"><%= @food.item_name %> の詳細</h1>
    <p>
      <strong>品名：</strong>
      <%= @food.item_name %>
    </p>
    <p>
      <strong>品種：</strong>
      <%= @food.variety %>
    </p>
    <p>
      <strong>内容:</strong>
      <%= @food.comment %>
    </p>
    <p>
      <strong>保存方法:</strong>
      <%= @food.storage_method %>
    </p>
    <p>
      <strong>収穫予定日:</strong>
      <%= @food.harvest %>
    </p>
    <p>
      <strong>価格:</strong>
      <%= @food.price %>
    </p>
    <p>
      <strong>在庫状況:</strong>
      <%= @food.stock %>
    </p>
  </div>

    <div class="button-white-small">
      <p class="arrow">
        <i class="fa-solid fa-angle-left"></i>
        <%= link_to 'トップページ', foods_path %>
      </p>
    </div>

    <% if current_user %>
      <div class="button-white-small">
        <p class="arrow">
          <i class="fa-solid fa-user"></i>
          <%= link_to 'マイページ', users_show_path %>
        </p>
      </div>
    <% end %>

    <% if current_user&.admin %>
      <div class="button-blue-small">
        <p class="arrow">
          <i class="fa-solid fa-pencil"></i>
          <%= link_to '編集', edit_food_path(@food) %>
        </p>
      </div>
      <div class="button-blue-small">
        <p class="arrow">
          <i class="fa-solid fa-trash-can"></i>
          <%= link_to '削除', food_path(@food), method: :delete, data: { confirm: '本当に消していいですか？' } %>
        </p>
      </div>
    <% end %>
  </div>
</div>

<script>
  $(function () {
    $(".js-sub-img img").on("click", function () {
      // メイン画像に切り替えるimgのsrc取得
      img = $(this).attr("src");
      // currentクラス付け替え(枠線などを変えたい時に)
      $(".js-sub-img li").removeClass("current");
      $(this).parent().addClass("current");
      // fadeOutできたらsrc変更してfadeIn
      $(".js-main-img img").fadeOut(500, function () {
        $(".js-main-img img")
          .attr("src", img)
          .on("load", function () {
            $(this).fadeIn(500);
          });
      });
    });
  });
</script>