config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users, controllers: { registrations: 'users/registrations',passwords: 'users/passwords'}
  # 以下を追加
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_sign_in', to: 'users/sessions#admin_sign_in'
  end
  resources :users, only: [:show, :edit, :update] do
    get :favorites, on: :collection
  end

  resources :foods do
    resource :favorites, only: [:create, :destroy]
  end
  post 'favorite/:id' => 'favorites#create', as: 'create_favorite'

  resources :plans do
    resources :comments
  end
  resources :favorites, only: [:favorites, :create, :destroy]
  root 'foods#index'
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  resources :contacts, only: [:new, :create, :destroy] 
  resources :maps, only: [:index]
  resources :others, only: [:index]
  resources :wethers, only: [:index]
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :plan
  validates :content, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :message, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :food
  validates_uniqueness_of :food_id, scope: :user_id

  # validates :user_id, presence: true
  # validates :food_id, presence: true
  # validates_uniqueness_of :food_id, scope: :user_id

  # def self.favorite_method(food, user)
  #   Favorite.find_by(food_id: food.id, user_id: user.id)
  # end
  # validates_uniqueness_of :food_id, scope: :user_id
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, optional: true

  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end

  validates :item_name,  presence: true, length: { maximum: 255 }
  validates :comment,  presence: true, length: { maximum: 255 }
  validates :harvest,  presence: true, length: { maximum: 255 }
  validates :price,  presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title,  presence: true
  validates :content,  presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods
  has_many :favorites, dependent: :destroy
  has_many :favorite_foods, through: :favorites, source: :food
  has_many :plans

  def favorited_by?(food_id)
    favorites.where(food_id: food_id).exists?
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end

  def self.admin
    find_or_create_by!(email: 'guest_admin@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "管理者ゲストユーザー"
      user.admin = true
    end
  end

  validates :name, presence: true

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy, :create]
  before_action :check_admin, only: [:new, :edit, :update, :destroy, :create]

  def index
    @foods = Food.all.order(created_at: :desc)
    @q = Food.ransack(params[:q])
    @foods = @q.result(distinct: true).order(created_at: :desc)
    @foods = @foods.page(params[:page]).per(8)
  end

  def show
    @favorite = Favorite.find_by(food_id: @food.id)
  end

  def new
    @food = Food.new
  end

  def edit
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      NoticeMailer.sendmail_food(@food).deliver
      redirect_to foods_path, notice: 'フードを新規登録しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: "フードの更新をしました" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: "フードを削除しました" }
    end
  end

  private

    def set_food
      @food = Food.find(params[:id])
    end

    def food_params
      params.require(:food).permit(:item_name, :variety, :comment, :storage_method, :harvest, :price, :stock, images: [])
    end

    def check_admin
      return if current_user.admin
      redirect_to root_path
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wethers_helper.rb
module WethersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>内山農園 in 細江</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=M+PLUS+1p:400,500" rel="stylesheet">
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-R38340MEB0"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-R38340MEB0');
    </script>
  </head>

  <body>
    <header class="header">
      <h1></h1>
        <nav>
          <ul class="list_nav_header">
            <% if user_signed_in? %>
              <li><%= link_to "マイページ", users_show_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
              <li><%= link_to '内山農園について', others_path %></li>
              <li><%= link_to 'お問い合わせ', new_contact_path %></li>
            <% else %>
              <li><%= link_to "新規登録", new_user_registration_path %></li>
              <li><%= link_to "ログイン", new_user_session_path %></li>
              <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %></li>
              <li><%= link_to '管理者ログイン（閲覧用）', users_admin_sign_in_path, method: :post %></li>
              <li><%= link_to '内山農園について', others_path %></li>
              <li><%= link_to 'お問い合わせ', new_contact_path %></li>
            <% end %>
          </ul>
          <div class="burger">
            <%= image_tag (asset_path'menu.png') %>
          </div>
          <div class="menu">
            <%= image_tag (asset_path'close.png') %>
            <ul class="list_nav_header">
              <% if user_signed_in? %>
                <li><%= link_to "マイページ", users_show_path %></li>
                <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                <li><%= link_to '内山農園について', others_path %></li>
                <li><%= link_to 'お問い合わせ', new_contact_path %></li>
              <% else %>
                <li><%= link_to "新規登録", new_user_registration_path %></li>
                <li><%= link_to "ログイン", new_user_session_path %></li>
                <li><%= link_to 'ゲストログイン（閲覧用）', users_guest_sign_in_path, method: :post %></li>
                <li><%= link_to '管理者ログイン（閲覧用）', users_admin_sign_in_path, method: :post %></li>
                <li><%= link_to '内山農園について', others_path %></li>
                <li><%= link_to 'お問い合わせ', new_contact_path %></li>
              <% end %>
            </ul>
          </div>
        </nav>
    </header>
    <div class="wrapper">
      <div class="logo">
        <%= link_to (foods_path) do%>
          <%= image_tag (asset_path'uchiyamafarmlogo.png') %>
        <% end%>
      </div>
      <div class="container">
        <%= yield %>
      </div>
    </div>
    <footer>
      <ul class="footer">
        <li><%= link_to 'トップページ', foods_path %></li>
        <li><%= link_to '内山農園について', others_path %></li>
        <li><%= link_to 'お問い合わせ', new_contact_path %></li>
      </ul>
      <p class="copyright">
        &copy; Uchiyama Farm in Hosoe
      </p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script>
      $(".burger").click(function () {
        $(".burger").toggleClass("is-active");
        $(".menu").toggleClass("is-active");
      });
    </script>
  </body>
</html>